version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
            filters:
              branches:
                only:
                  - main
            requires:
              - build

jobs:
  build:
    working_directory: ~/NewsFinder
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: update-npm
          command: 'sudo npm install -g npm@8.1.4'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install       
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: audit-packages
          command: npm audit
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: 
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image
          command: docker push $IMAGE_NAME
      - run:
          name: set-environment-variables
          command: echo $SERVER > server.crt && echo $PRIVATE_KEY > privatekey.pem
      - run:
          name: build-docker-image-for-integration-environment
          command: docker create -p 8443:8443 --name newsfinder $IMAGE_NAME
      - run:
          name: copy-server-cert-and-private-key-across
          command: docker cp ./privatekey.pem newsfinder:/privatekey.pem; docker cp ./server.crt newsfinder:/server.crt
      - run:
          name: start-docker-container
          command: docker start newsfinder

  deploy: 
    docker:
      - image: circleci/node:latest
    steps:
      - run: 
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export SERVER=\"$SERVER\"; export PRIVATE_KEY=\"$PRIVATE_KEY\"; export GUARDIAN_API_KEY=\"$GUARDIAN_API_KEY\"; rm -rf NewsFinder/;git clone https://github.com/AdamRNCI/NewsFinder.git; source NewsFinder/deploy.sh"